// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwrkqgehskgmzqakutuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3cmtxZ2Voc2tnbXpxYWt1dHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODg2NDAsImV4cCI6MjA2Mzg2NDY0MH0.K_Ro05mHljX-I8bgNOkOSNZJ2NPIc688FhcIohrsJPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);